services:
  - type: web
    name: ny-tagging-sys
    env: docker
    plan: free
    region: singapore
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8001
      - key: DATABASE_URL
        value: sqlite:///database.db
      - key: BARTENDER_WATCH_FOLDER
        value: /app/print_jobs
      - key: TZ
        value: Asia/Ho_Chi_Minh
    autoDeploy: true
