services:
  - type: web
    name: ny-tagging-sys
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDirectory: backend_v2
    envVars:
      - key: PORT
        value: 8001
      - key: DATABASE_URL
        value: sqlite:///database.db
      - key: TZ
        value: Asia/Ho_Chi_Minh
    autoDeploy: true
